export enum ApiErrorCode {
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  NOT_FOUND = "NOT_FOUND",
  UNIT_UNAVAILABLE = "UNIT_UNAVAILABLE",
  RESERVATION_CONFLICT = "RESERVATION_CONFLICT",
  PAYMENT_FAILED = "PAYMENT_FAILED",
  CAPACITY_UNAVAILABLE = "CAPACITY_UNAVAILABLE",
  INVALID_CHECK_IN = "INVALID_CHECK_IN",
  PRICING_NOT_CONFIGURED = "PRICING_NOT_CONFIGURED",
  HOLD_CONFLICT = "HOLD_CONFLICT",
  HOLD_EXPIRED = "HOLD_EXPIRED",
  OUT_OF_FACILITY_SCOPE = "OUT_OF_FACILITY_SCOPE",
  BOOKING_NOT_FOUND = "BOOKING_NOT_FOUND",
  PHYSICAL_UNIT_NOT_FOUND = "PHYSICAL_UNIT_NOT_FOUND",
  INVALID_UNIT_ASSIGNMENT = "INVALID_UNIT_ASSIGNMENT",
  UNIT_ASSIGNMENT_CONFLICT = "UNIT_ASSIGNMENT_CONFLICT",
  STAFF_NOT_IN_FACILITY = "STAFF_NOT_IN_FACILITY",
  INVALID_STAFF_ROLE = "INVALID_STAFF_ROLE",
  STAFF_INACTIVE = "STAFF_INACTIVE",
}

export type { ApiEnvelope, ApiErrorBody, PaginatedResult } from "./api-response.types";
