export const Permission = {
  VIEW_FACILITIES: "VIEW_FACILITIES",
  CREATE_RESERVATION: "CREATE_RESERVATION",
  VIEW_OWN_RESERVATIONS: "VIEW_OWN_RESERVATIONS",
  VIEW_ASSIGNED_FACILITY: "VIEW_ASSIGNED_FACILITY",
  MANAGE_STORAGE_UNITS: "MANAGE_STORAGE_UNITS",
  HANDLE_CHECK_IN: "HANDLE_CHECK_IN",
  HANDLE_RETURN: "HANDLE_RETURN",
  VIEW_FACILITY_REPORTS: "VIEW_FACILITY_REPORTS",
  VIEW_SYSTEM_REPORTS: "VIEW_SYSTEM_REPORTS",
  MANAGE_USERS: "MANAGE_USERS",
  MANAGE_ROLES: "MANAGE_ROLES",
  VIEW_ACTIVITY_LOGS: "VIEW_ACTIVITY_LOGS",
} as const;

export type Permission = (typeof Permission)[keyof typeof Permission];
