import { UserRole as Role } from "@metastorage/contracts";
import type { AdminMockData } from "./admin.types";

export const adminMockData: AdminMockData = {
  facilities: [
    { id: "SGC", name: "StoreX Sài Gòn Central", address: "Quận 7, TP. Hồ Chí Minh" },
    { id: "BTL", name: "StoreX Bình Thạnh", address: "Bình Thạnh, TP. Hồ Chí Minh" },
    { id: "CG", name: "StoreX Cầu Giấy", address: "Cầu Giấy, Hà Nội" },
    { id: "NSG", name: "StoreX Nam Sài Gòn", address: "Nhà Bè, TP. Hồ Chí Minh" },
  ],
  users: [
    {
      id: "demo-admin",
      name: "Nguyễn Văn Hùng",
      email: "hung.admin@example.test",
      role: Role.SYSTEM_ADMINISTRATOR,
      status: "ACTIVE",
      facilityIds: [],
      lastLoginAt: "2026-10-08T09:15:00+07:00",
    },
    {
      id: "demo-manager",
      name: "Lê Thu Hà",
      email: "ha.manager@example.test",
      role: Role.FACILITY_MANAGER,
      status: "ACTIVE",
      facilityIds: ["SGC", "BTL"],
      lastLoginAt: "2026-10-08T08:45:00+07:00",
    },
    {
      id: "demo-staff-1",
      name: "Nguyễn Minh Hoàng",
      email: "hoang.staff@example.test",
      role: Role.FACILITY_STAFF,
      status: "ACTIVE",
      facilityIds: ["SGC"],
      lastLoginAt: "2026-10-08T08:30:00+07:00",
    },
    {
      id: "demo-staff-2",
      name: "Vũ Hữu Đạt",
      email: "dat.staff@example.test",
      role: Role.FACILITY_STAFF,
      status: "ACTIVE",
      facilityIds: [],
      lastLoginAt: null,
    },
    {
      id: "demo-operations",
      name: "Vũ Minh Hoàng",
      email: "hoang.operations@example.test",
      role: Role.BUSINESS_OPERATIONS_MANAGER,
      status: "ACTIVE",
      facilityIds: [],
      lastLoginAt: "2026-10-08T08:10:00+07:00",
    },
    {
      id: "demo-customer",
      name: "Lê Thị Mai Linh",
      email: "linh.customer@example.test",
      role: Role.STORAGE_CUSTOMER,
      status: "INACTIVE",
      facilityIds: [],
      lastLoginAt: "2026-10-07T15:00:00+07:00",
    },
  ],
  logins: [
    {
      id: "LOGIN-001",
      userId: "demo-admin",
      name: "Nguyễn Văn Hùng",
      email: "hung.admin@example.test",
      role: Role.SYSTEM_ADMINISTRATOR,
      at: "2026-10-08T09:15:00+07:00",
      ipMasked: "118.69.xxx.12",
      device: "Chrome / Windows",
      outcome: "SUCCESS",
    },
    {
      id: "LOGIN-002",
      userId: "demo-manager",
      name: "Lê Thu Hà",
      email: "ha.manager@example.test",
      role: Role.FACILITY_MANAGER,
      at: "2026-10-08T08:45:00+07:00",
      ipMasked: "14.161.xxx.99",
      device: "Safari / iOS",
      outcome: "SUCCESS",
    },
    {
      id: "LOGIN-003",
      userId: "demo-staff-1",
      name: "Nguyễn Minh Hoàng",
      email: "hoang.staff@example.test",
      role: Role.FACILITY_STAFF,
      at: "2026-10-08T08:30:00+07:00",
      ipMasked: "171.244.xxx.88",
      device: "Chrome / Android",
      outcome: "SUCCESS",
    },
    {
      id: "LOGIN-004",
      userId: "demo-customer",
      name: "Lê Thị Mai Linh",
      email: "linh.customer@example.test",
      role: Role.STORAGE_CUSTOMER,
      at: "2026-10-08T08:20:00+07:00",
      ipMasked: "42.113.xxx.45",
      device: "Edge / Windows",
      outcome: "FAILED",
    },
    {
      id: "LOGIN-005",
      userId: "demo-operations",
      name: "Vũ Minh Hoàng",
      email: "hoang.operations@example.test",
      role: Role.BUSINESS_OPERATIONS_MANAGER,
      at: "2026-10-08T08:10:00+07:00",
      ipMasked: "125.235.xxx.15",
      device: "Safari / macOS",
      outcome: "SUCCESS",
    },
  ],
  audits: [
    {
      id: "AUD-001",
      actor: "Nguyễn Văn Hùng",
      actorRole: Role.SYSTEM_ADMINISTRATOR,
      target: "Lê Thu Hà",
      targetId: "demo-manager",
      action: "FACILITIES_CHANGED",
      at: "2026-10-08T09:05:00+07:00",
      outcome: "SUCCESS",
      facilityIds: ["SGC", "BTL"],
      reason: "Bổ sung phạm vi cơ sở trong dữ liệu mẫu",
      before: { role: Role.FACILITY_MANAGER, status: "ACTIVE", facilityIds: ["SGC"] },
      after: { role: Role.FACILITY_MANAGER, status: "ACTIVE", facilityIds: ["SGC", "BTL"] },
    },
    {
      id: "AUD-002",
      actor: "Nguyễn Văn Hùng",
      actorRole: Role.SYSTEM_ADMINISTRATOR,
      target: "Lê Thị Mai Linh",
      targetId: "demo-customer",
      action: "STATUS_CHANGED",
      at: "2026-10-08T08:55:00+07:00",
      outcome: "SUCCESS",
      facilityIds: [],
      reason: "Mô phỏng trạng thái khóa",
      before: { role: Role.STORAGE_CUSTOMER, status: "ACTIVE", facilityIds: [] },
      after: { role: Role.STORAGE_CUSTOMER, status: "INACTIVE", facilityIds: [] },
    },
  ],
};
